---
title: 
author: 
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning=F)
```

```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(tidyverse, ggforce)

# Parameters
df <- read_csv("sna_handbook_eric.csv")
```

```{r}
df %>% glimpse()
```




```{r, fig.retina=4}
df %>% 
  mutate(
    #Domain = str_to_title(Domain),
    Domain = fct_reorder2(Domain, Year, prop_articles)
  ) %>% 
  ggplot(aes(x = Year)) +
  geom_line(aes(y = prop_articles, color = Domain)) +
  #geom_smooth(aes(y = prop_articles, color = Domain), se = F, method = "loess") +
  scale_x_continuous(breaks = scales::breaks_width(5)) +
  #facet_zoom(y = (Domain != "Social Network")) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_bw() +
  labs(
    x = "Year of publication",
    y = "Domain articles / Education articles (%)",
    #title = "Growth in EDS relative to the Education corpus",
    color = "Domain",
    #caption = "Source: Data sourced from ERIC API"
  )
  
ggsave(here::here("figure_v3.png"), units = "in", height = 4, width = 6, dpi = "retina")
```

